import os
import time
import glob
import subprocess
import logging
from services.mt5_gateway import gateway_client

logger = logging.getLogger("base_service")


class BaseService:
    """
    Base service providing connection management, auto-recovery, and environment diagnostics for MetaTrader 5.
    """

    _initialized: bool = False

    @classmethod
    def _inspect_and_dismiss_modal_windows(cls) -> None:
        """
        Dismiss any pending first-use modal dialogs (e.g. account setup wizards) via xdotool in Xvfb.
        """
        try:
            subprocess.run(["xdotool", "key", "Escape"], capture_output=True, timeout=1)
        except Exception:
            pass

    @classmethod
    def _dump_diagnostics(cls, path: str) -> None:
        """
        Dump active Linux processes and MT5/Wine terminal logs for troubleshooting startup failures.

        Args:
            path (str): Expected path to MT5 terminal binary.
        """
        logger.info("=== WINE / MT5 ENVIRONMENT DIAGNOSTICS ===")
        # 1. Active Linux processes inside container
        try:
            res = subprocess.run(
                ["ps", "aux"], capture_output=True, text=True, timeout=5
            )
            logger.info(
                "Active processes inside container:\n%s", res.stdout or res.stderr
            )
        except Exception as e:
            logger.warning("Failed to execute ps aux: %s", e)

        # 2. Internal logs generated by MT5
        try:
            wineprefix = os.environ.get("WINEPREFIX", "/home/mt5user/.mt5")
            mt5_dir = os.path.join(
                wineprefix, "drive_c", "Program Files", "MetaTrader 5"
            )
            log_patterns = [
                os.path.join(mt5_dir, "logs", "*.log"),
                os.path.join(mt5_dir, "MQL5", "Logs", "*.log"),
                os.path.join(mt5_dir, "MQL5", "Experts", "*.log"),
            ]
            for pattern in log_patterns:
                for fpath in glob.glob(pattern):
                    with open(fpath, "r", errors="ignore") as f:
                        lines = f.readlines()[-15:]
                        logger.info("Last lines of %s:\n%s", fpath, "".join(lines))
        except Exception as e:
            logger.warning("Failed to check MT5 logs: %s", e)
        logger.info("===========================================")

    @classmethod
    def ensure_initialized(cls, retries: int = 15, delay: float = 1.0) -> bool:
        """
        Verify connection to the MetaTrader 5 TCP RestGateway socket, retrying if necessary.

        Args:
            retries (int, optional): Number of connection retry attempts. Defaults to 15.
            delay (float, optional): Seconds to wait between retries. Defaults to 1.0.

        Returns:
            bool: True if connected.

        Raises:
            RuntimeError: If connection cannot be established after all retries.
        """
        if cls._initialized:
            return True

        logger.info(
            "Verifying connection to MetaTrader 5 via TCP Gateway (%s:%d)...",
            gateway_client.host,
            gateway_client.port,
        )

        last_err = None
        for attempt in range(1, retries + 1):
            try:
                # 1. Dismiss any pending modal dialogs in Wine
                cls._inspect_and_dismiss_modal_windows()

                # 2. Test ping via pure TCP Socket Gateway
                if gateway_client.ping():
                    cls._initialized = True
                    logger.info(
                        "MT5 TCP Gateway connected successfully at %s:%d! Version: %s",
                        gateway_client.host,
                        gateway_client.port,
                        gateway_client.version(),
                    )
                    return True

                last_err = f"TCP Gateway did not respond on {gateway_client.host}:{gateway_client.port}"
                logger.info(
                    "Attempt %d/%d: Waiting for TCP Gateway initialization...",
                    attempt,
                    retries,
                )

            except Exception as e:
                last_err = e
                logger.warning(
                    "Attempt %d/%d: Gateway verification error: %s", attempt, retries, e
                )

            if attempt < retries:
                time.sleep(delay)

        cls._initialized = False
        cls._dump_diagnostics(
            os.environ.get("MT5_PATH", "C:/Program Files/MetaTrader 5/terminal64.exe")
        )
        raise RuntimeError(f"MT5 Gateway initialization failed: {last_err}")

